/**
 * Sprint 15 – browser end-to-end check (password reset, beta onboarding,
 * landing-page CTAs).
 *
 * Runs against the REAL Worker build (`npm run cf:build` + `opennextjs-cloudflare
 * preview`, workerd + local D1) with clearly labelled test accounts
 * (`<role>-<run>@innercircle.test`, names end with "(Testkonto)"). It is NOT
 * part of `npm test` and adds no dependency to the project: the browser
 * packages live outside the repository.
 *
 *   mkdir -p /tmp/pw && cd /tmp/pw && npm i playwright-core @sparticuz/chromium
 *   PW_MODULES=/tmp/pw/node_modules BASE_URL=http://127.0.0.1:8787 \
 *     node tests/e2e/sprint15-browser.mjs
 *
 * Requirements: local D1 migrated + bootstrapped, `.dev.vars` with
 *   NEXT_PUBLIC_SITE_URL=<production URL> (the script asserts that the
 *   reset link and the admin invitation text use EXACTLY this origin),
 *   ENABLE_DEV_OUTBOX=true and DEV_OUTBOX_RECIPIENTS=@innercircle.test.
 * The script only ever touches the LOCAL database (`wrangler d1 execute
 * --local`) and refuses to run against anything but localhost.
 *
 * Honest scope: no external mailbox is reachable from the sandbox. The
 * password-reset e-mail is read from the dev outbox (identical content to
 * what Resend receives) and the extracted link is opened in the browser with
 * its origin rewritten from NEXT_PUBLIC_SITE_URL to the local worker – the
 * token flow itself runs completely inside the real Worker build.
 *
 * Output: screenshots in preview/sprint15/, results as JSON in $E2E_OUT
 * (default /tmp/e2e-results-<run>.json). Exit code 1 if any check fails.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PW_MODULES = process.env.PW_MODULES ?? "/tmp/pw/node_modules";
const BASE = process.env.BASE_URL ?? "http://127.0.0.1:8787";
const REPO = fileURLToPath(new URL("../..", import.meta.url));
const SHOTS = join(REPO, "preview", "sprint15");
const RUN = String(Date.now());
const OUT = process.env.E2E_OUT ?? `/tmp/e2e-results-${RUN}.json`;
const PASSWORD = "Testing!2026";
const NEW_PASSWORD = "NeuesPasswort1";

if (!/^https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(BASE)) {
  console.error(`Refusing to run against ${BASE} – local preview only.`);
  process.exit(2);
}

/** The origin production links must use – read from `.dev.vars`, never hardcoded. */
const SITE_URL = (readFileSync(join(REPO, ".dev.vars"), "utf8").match(/^NEXT_PUBLIC_SITE_URL=(.+)$/m) ?? [])[1]?.trim();
if (!/^https:\/\//.test(SITE_URL ?? "")) {
  console.error("`.dev.vars` must define an https NEXT_PUBLIC_SITE_URL (production mirror).");
  process.exit(2);
}

const { chromium } = await import(pathToFileURL(join(PW_MODULES, "playwright-core", "index.mjs")).href);
const sparticuz = (await import(pathToFileURL(join(PW_MODULES, "@sparticuz", "chromium", "build", "index.js")).href))
  .default;

// The bundled NSS/NSPR runtime ships in al2023.tar.br and is only extracted
// automatically on Amazon Linux – extract it once and put it on the loader path.
const al2023Lib = "/tmp/al2023/lib";
if (!existsSync(join(al2023Lib, "libnss3.so"))) {
  const { inflate } = await import(pathToFileURL(join(PW_MODULES, "@sparticuz", "chromium", "build", "lambdafs.js")).href);
  await inflate(join(PW_MODULES, "@sparticuz", "chromium", "bin", "al2023.tar.br"));
}
process.env.LD_LIBRARY_PATH = process.env.LD_LIBRARY_PATH?.startsWith(al2023Lib)
  ? process.env.LD_LIBRARY_PATH
  : [al2023Lib, process.env.LD_LIBRARY_PATH].filter(Boolean).join(":");

/* ------------------------------------------------------------ helpers */

const results = [];
function check(ok, name, detail = "") {
  results.push({ ok: Boolean(ok), name, detail: String(detail) });
  console.log(`${ok ? "PASS" : "FAIL"} · ${name}${detail ? ` · ${detail}` : ""}`);
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** Local D1 only. Values in queries are generated by this script, never user input. */
function sql(query) {
  const out = execFileSync("npx", ["wrangler", "d1", "execute", "DB", "--local", "--json", "--command", query], {
    cwd: REPO,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
  return JSON.parse(out).flatMap((entry) => entry.results ?? []);
}

mkdirSync(SHOTS, { recursive: true });
const browser = await chromium.launch({
  executablePath: await sparticuz.executablePath(),
  headless: true,
  // Not sparticuz.args: its --single-process mode loses cookies in a 2nd context.
  args: ["--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu", "--no-zygote"],
});

async function newContext({ mobile = false, locale = "de", theme = "light" } = {}) {
  const context = await browser.newContext({
    viewport: mobile ? { width: 390, height: 844 } : { width: 1440, height: 900 },
    deviceScaleFactor: mobile ? 2 : 1,
    isMobile: mobile,
    hasTouch: mobile,
    colorScheme: theme,
    locale: locale === "de" ? "de-DE" : "en-US",
  });
  await context.addInitScript(
    ([loc, th, withCls]) => {
      try {
        localStorage.setItem("ic-locale", loc);
        localStorage.setItem("ic-theme", th);
      } catch {
        /* storage unavailable – defaults apply */
      }
      if (withCls) {
        try {
          window.__cls = 0;
          new PerformanceObserver((list) => {
            for (const entry of list.getEntries()) {
              if (!entry.hadRecentInput) window.__cls += entry.value;
            }
          }).observe({ type: "layout-shift", buffered: true });
        } catch {
          /* observer unsupported – metric stays undefined */
        }
      }
    },
    [locale, theme, true],
  );
  return context;
}

async function shot(page, name, { fullPage = false } = {}) {
  await page.waitForLoadState("networkidle").catch(() => {});
  await page.waitForTimeout(500);
  await page.screenshot({ path: join(SHOTS, `${name}.png`), fullPage });
}

const visibleText = (page, text) => page.getByText(text, { exact: false }).filter({ visible: true }).first();
async function isVisible(page, text, timeout = 0) {
  if (timeout > 0) {
    try {
      await visibleText(page, text).waitFor({ state: "visible", timeout });
      return true;
    } catch {
      return false;
    }
  }
  return visibleText(page, text).isVisible();
}

async function waitForCode(email) {
  for (let attempt = 0; attempt < 30; attempt++) {
    const rows = sql(`select body from DevOutbox where "to" = '${email}' order by createdAt desc limit 1`);
    const match = rows[0]?.body?.match(/\b(\d{6})\b/);
    if (match) return match[1];
    await sleep(500);
  }
  throw new Error(`no verification code for ${email}`);
}

async function register(page, { first, last, email }) {
  await page.goto(`${BASE}/register`);
  await page.fill('input[name="firstName"]', first);
  await page.fill('input[name="lastName"]', last);
  await page.fill('input[name="email"]', email);
  await page.fill('input[name="password"]', PASSWORD);
  await page.fill('input[name="passwordConfirm"]', PASSWORD);
  await page.check('input[name="age"]');
  await page.check('input[name="terms"]');
  await page.locator('form:has(input[name="firstName"]) button[type="submit"]').click();
  await page.waitForURL(/\/verify/, { timeout: 45000 });
  await page.fill('input[name="code"]', await waitForCode(email));
  await page.locator('form:has(input[name="code"]) button[type="submit"]').first().click();
  await page.waitForURL(/\/onboarding|\/app/, { timeout: 45000 });
}

async function onboard(page, interests, goal) {
  if (!/\/onboarding/.test(page.url())) await page.goto(`${BASE}/onboarding/interests`);
  for (const label of interests) {
    await page
      .locator("button[aria-pressed]")
      .filter({ hasText: new RegExp(`^\\s*${escapeRegExp(label)}\\s*$`) })
      .first()
      .click();
  }
  await page.locator("button[aria-pressed]").filter({ hasText: goal }).last().click();
  await page.locator('form:has(input[name="startTrial"]) button[type="submit"]').click();
  await page.waitForURL((url) => url.pathname.startsWith("/app"), { timeout: 45000 });
}

async function login(page, email, password) {
  await page.goto(`${BASE}/login`);
  await page.fill('input[name="identifier"]', email);
  await page.fill('input[name="password"]', password);
  await page.locator('form:has(input[name="identifier"]) button[type="submit"]').click();
}

async function fillWelcomeProfile(page, fields) {
  for (const [name, value] of Object.entries(fields)) await page.fill(`[name="${name}"]`, value);
  await page.getByRole("button", { name: "Speichern & Netzwerk entdecken" }).click();
  await page.waitForURL(/\/app\/discover/, { timeout: 45000 });
}

/**
 * Fills the reset form hydration-safe: the inputs are React-controlled, so a
 * value typed before hydration is dropped on the first re-render. Wait for the
 * field, fill both inputs and verify the value actually stuck.
 */
async function fillResetForm(page, password) {
  await page.locator('input[name="password"]').first().waitFor({ state: "visible", timeout: 20000 });
  await page.waitForTimeout(700);
  for (let attempt = 0; attempt < 3; attempt++) {
    await page.fill('input[name="password"]', password);
    await page.fill('input[name="passwordConfirm"]', password);
    if ((await page.inputValue('input[name="password"]')) === password) return;
    await page.waitForTimeout(500);
  }
  throw new Error("password field did not retain the typed value");
}

async function createKey(admin, label, email = "") {
  await admin.goto(`${BASE}/admin/beta`);
  await admin.fill('input[name="label"]', `${label} ${RUN}`);
  await admin.fill('input[name="restrictedEmail"]', email);
  await admin.getByRole("button", { name: "Schlüssel erstellen" }).click();
  const key = admin.locator('[data-testid="beta-key"]');
  await key.waitFor({ state: "visible", timeout: 20000 });
  return (await key.innerText()).trim();
}

const emails = Object.fromEntries(
  ["admin", "rita", "bea", "carl"].map((role) => [role, `${role}-${RUN}@innercircle.test`]),
);

/* ------------------------------------------------------------ run */

try {
  // Clean slate for the labelled test data only (local D1).
  sql(
    "DELETE FROM User WHERE email LIKE '%@innercircle.test'; DELETE FROM BetaInvite; DELETE FROM RateLimit; DELETE FROM DevOutbox;",
  );

  /* =============================================== A · landing-page CTAs
     Desktop DE/EN + mobile DE/EN: „Mehr erfahren“ first and blue, „Zur INNER
     CIRCLE Plattform“ second, anchor target exists, no layout shift. */
  const CTA = {
    de: { primary: "Mehr erfahren", secondary: "Zur INNER CIRCLE Plattform" },
    en: { primary: "Learn more", secondary: "Go to the INNER CIRCLE platform" },
  };
  const BLUE = "rgb(54, 108, 245)";
  for (const locale of ["de", "en"]) {
    for (const mobile of [false, true]) {
      const combo = `${locale}-${mobile ? "mobile" : "desktop"}`;
      const ctx = await newContext({ mobile, locale });
      const page = await ctx.newPage();
      await page.goto(`${BASE}/`, { waitUntil: "networkidle" }).catch(() => {});
      await page.waitForTimeout(700);

      check(await isVisible(page, "A stronger"), `hero headline renders (${combo})`);

      const pair = await page.evaluate(() => {
        const first = [...document.querySelectorAll('a[href="#outcomes"]')].find(
          (a) => a.getBoundingClientRect().width > 0,
        );
        if (!first) return null;
        const box = first.parentElement;
        return [...box.querySelectorAll("a")]
          .filter((a) => a.getBoundingClientRect().width > 0)
          .map((a) => ({
            href: a.getAttribute("href"),
            text: (a.textContent || "").replace(/\s+/g, " ").trim(),
            bg: getComputedStyle(a).backgroundColor,
          }));
      });
      check(Array.isArray(pair) && pair.length === 2, `exactly two hero CTAs (${combo})`, JSON.stringify(pair));
      if (Array.isArray(pair) && pair.length === 2) {
        check(pair[0].text === CTA[locale].primary, `first CTA is „${CTA[locale].primary}“ (${combo})`, pair[0].text);
        check(pair[0].href === "#outcomes", `first CTA points to #outcomes (${combo})`, pair[0].href);
        check(pair[0].bg === BLUE, `first CTA is blue/electric (${combo})`, pair[0].bg);
        check(pair[1].text === CTA[locale].secondary, `second CTA is „${CTA[locale].secondary}“ (${combo})`, pair[1].text);
        check(pair[1].href === "/app", `second CTA points to /app (${combo})`, pair[1].href);
        check(pair[1].bg !== BLUE, `second CTA is not the blue primary (${combo})`, pair[1].bg);
      }

      const cls = await page.evaluate(() => window.__cls);
      check(typeof cls === "number" && cls < 0.1, `no layout shift on the hero (${combo})`, `CLS=${cls}`);

      const noScroll = await page.evaluate(
        () => document.documentElement.scrollWidth <= window.innerWidth + 1,
      );
      check(noScroll, `no horizontal scroll (${combo})`);
      await shot(page, `01-cta-${combo}`);

      // Anchor works (click), then – desktop DE only – the platform link goes
      // to the login flow (anonymous visitor).
      await page.locator('a[href="#outcomes"]').filter({ visible: true }).first().click();
      await page.waitForTimeout(900);
      const anchored = await page.evaluate(() => ({
        hash: location.hash,
        scrollY: window.scrollY,
        inView: (() => {
          const el = document.getElementById("outcomes");
          if (!el) return false;
          const rect = el.getBoundingClientRect();
          return rect.top < window.innerHeight && rect.bottom > 0;
        })(),
      }));
      check(anchored.hash === "#outcomes" && anchored.inView, `„Mehr erfahren“ scrolls to the info section (${combo})`, JSON.stringify(anchored));

      if (!mobile && locale === "de") {
        await page.locator('a[href="/app"]').filter({ visible: true }).nth(1).click();
        await page.waitForURL(/\/login/, { timeout: 30000 }).catch(() => {});
        check(/\/login/.test(page.url()), "platform CTA leads anonymous visitors into the login flow", page.url());
      }
      await ctx.close();
    }
  }

  /* ================================================= B · password reset */

  // 1. Register + verify + onboard a real account through the UI.
  const resetCtx = await newContext();
  const resetPage = await resetCtx.newPage();
  await register(resetPage, { first: "Rita", last: "Reset (Testkonto)", email: emails.rita });
  await onboard(resetPage, ["Unternehmertum", "Startups", "Investieren"], "Netzwerk aufbauen");
  check(new URL(resetPage.url()).pathname.startsWith("/app"), "tester account ready for the reset flow");

  // 2. Login page → „Passwort vergessen“ → request the link.
  await resetPage.goto(`${BASE}/login`);
  check(await isVisible(resetPage, "Passwort vergessen?"), "login page shows „Passwort vergessen?“");
  await resetPage.locator('a[href="/forgot-password"]').filter({ visible: true }).first().click();
  await resetPage.waitForURL(/\/forgot-password/, { timeout: 30000 });
  await resetPage.fill('input[name="email"]', emails.rita);
  await resetPage.locator('form:has(input[name="email"]) button[type="submit"]').click();
  check(
    await isVisible(resetPage, "Anfrage erhalten", 20000),
    "generic success without account enumeration",
  );
  check(
    await isVisible(resetPage, "Aus Sicherheitsgründen zeigen wir nicht"),
    "success text explains the anti-enumeration behaviour",
  );
  await shot(resetPage, "02-forgot-sent");

  // 3. The mail in the outbox: branded, absolute, production origin, no localhost.
  const mails = sql(
    `select subject, body from DevOutbox where "to" = '${emails.rita}' and template = 'password_reset' order by createdAt desc limit 1`,
  );
  check(mails.length === 1, "reset mail was recorded (mail transport mocked by the dev outbox)");
  const mailBody = mails[0]?.body ?? "";
  const subject = mails[0]?.subject ?? "";
  check(subject === "Passwort für INNER CIRCLE zurücksetzen", "mail subject matches the brand wording", subject);
  const mailLink = mailBody.match(/https?:\/\/[^\s"<>]+\/reset-password\?token=[A-Za-z0-9_-]+/)?.[0];
  check(Boolean(mailLink), "mail contains an absolute reset link", mailLink ?? mailBody.slice(0, 200));
  if (mailLink) {
    const url = new URL(mailLink);
    check(url.origin === SITE_URL, "link origin equals the configured NEXT_PUBLIC_SITE_URL", `${url.origin} vs ${SITE_URL}`);
    check(url.pathname === "/reset-password", "link path is the reset route", url.pathname);
    check(!mailLink.includes("localhost"), "link contains no localhost");
    check(!url.searchParams.get("redirect"), "link carries no open redirect parameter");
    check(mailBody.includes("um ein neues Passwort zu vergeben"), "mail text contains the call to open the link");
  check(mailBody.includes("neues Passwort"), "mail text uses the new-password wording");
    check(mailBody.includes("60 Minuten"), "mail states the expiry time");
    check(mailBody.includes("ignoriere diese E-Mail"), "mail contains the ignore hint");
  }

  // 4. Open the link (origin rewritten to the local worker – same path+token).
  const localLink = mailLink
    ? new URL(`${new URL(mailLink).pathname}${new URL(mailLink).search}`, BASE).toString()
    : "";
  const mailCtx = await newContext(); // fresh browser profile, like a mail client click
  const mailPage = await mailCtx.newPage();
  await mailPage.goto(localLink, { waitUntil: "domcontentloaded" });
  check(await isVisible(mailPage, "Neues Passwort vergeben", 20000), "reset page opens directly (no interstitial)");
  check(await mailPage.locator('input[name="password"]').isVisible(), "new-password field is present");
  check(await mailPage.locator('input[name="passwordConfirm"]').isVisible(), "confirmation field is present");
  check(await isVisible(mailPage, "Mindestens 10 Zeichen"), "password requirements are visible");
  check(await isVisible(mailPage, "Mindestens eine Zahl"), "password requirements include the digit rule");
  await shot(mailPage, "03-reset-form");

  // 5. Save the new password → redirected to the login.
  await fillResetForm(mailPage, NEW_PASSWORD);
  await mailPage.locator('form:has(input[name="password"]) button[type="submit"]').click();
  await mailPage.waitForURL(/\/login\?reset=1/, { timeout: 45000 }).catch(() => {});
  check(/\/login\?reset=1/.test(mailPage.url()), "successful reset lands on /login?reset=1", mailPage.url());

  // 6. Old password fails, new password signs in.
  await login(mailPage, emails.rita, PASSWORD);
  check(await isVisible(mailPage, "E-Mail-Adresse oder Passwort nicht korrekt.", 15000), "old password no longer works");
  await login(mailPage, emails.rita, NEW_PASSWORD);
  await mailPage.waitForURL((url) => url.pathname.startsWith("/app"), { timeout: 45000 }).catch(() => {});
  check(new URL(mailPage.url()).pathname.startsWith("/app"), "login with the new password works", mailPage.url());
  await shot(mailPage, "04-login-new-password");

  // 7. The same link is dead afterwards (single use) – the form accepts the
  // submission but the server refuses the already-used token.
  const replayCtx = await newContext();
  const replayPage = await replayCtx.newPage();
  await replayPage.goto(localLink, { waitUntil: "domcontentloaded" });
  await fillResetForm(replayPage, NEW_PASSWORD);
  await replayPage.locator('form:has(input[name="password"]) button[type="submit"]').click();
  check(
    await isVisible(replayPage, "Dieser Link ist ungültig oder abgelaufen.", 20000),
    "used token is refused (single use)",
  );
  await shot(replayPage, "05-token-replayed");
  await replayCtx.close();

  /* ==================================================== C · beta onboarding */

  // Admin: register, promote locally, create a key, invitation URL check.
  const adminCtx = await newContext();
  const admin = await adminCtx.newPage();
  await register(admin, { first: "Ada", last: "Admin (Testkonto)", email: emails.admin });
  await onboard(admin, ["Unternehmertum", "Startups", "Investieren"], "Netzwerk aufbauen");
  execFileSync("npx", ["tsx", "scripts/admin-bootstrap.ts", `--email=${emails.admin}`, "--local"], {
    cwd: REPO,
    stdio: "ignore",
  });
  await admin.goto(`${BASE}/admin/beta`);
  check(((await admin.locator("h1").first().innerText()) ?? "").includes("Private Beta"), "admin opens /admin/beta");

  const key = await createKey(admin, "Sprint15 E2E");
  check(/^ICB-[0-9A-HJKMNP-TV-Z]{4}(-[0-9A-HJKMNP-TV-Z]{4}){3}$/.test(key), "admin created a personal ICB key", key.slice(-4));
  const invite = await admin.locator('p:has-text("Registriere dich unter")').first().innerText();
  check(invite.includes(SITE_URL), "invitation text uses the configured production URL", SITE_URL);
  check(!invite.includes("localhost"), "invitation text contains no localhost");
  check(invite.includes("/register") && invite.includes("/app/beta"), "invitation text links register + redemption page");
  const plainHits = Number(
    sql(
      `select count(*) as n from BetaInvite where codeHash like '%${key}%' or ifnull(label,'') like '%${key}%'`,
    )[0].n,
  );
  check(plainHits === 0, "database stores no plain-text key");
  await shot(admin, "06-admin-invite");

  const boundKey = await createKey(admin, "Email binding regression", emails.carl.toUpperCase());

  // Tester: register → verify → onboarding → /app/beta → redeem.
  const testerCtx = await newContext();
  const tester = await testerCtx.newPage();
  await register(tester, { first: "Bea", last: "Beta (Testkonto)", email: emails.bea });
  await onboard(tester, ["Startups", "Vertrieb", "Business Development"], "Geschäftspartner finden");
  await tester.goto(`${BASE}/app/beta`);
  check(await isVisible(tester, "Beta-Zugang aktivieren"), "verified free tester opens /app/beta");
  check(await isVisible(tester, "Im Beta-Zugang enthalten"), "tester sees the unlocked features");

  await tester.fill('input[name="key"]', "ICB-0000-0000-0000-0000");
  await tester.locator('form:has(input[name="key"]) button[type="submit"]').click();
  check(await isVisible(tester, "Dieser Beta-Schlüssel ist ungültig", 20000), "invalid key is refused clearly");
  await shot(tester, "07-beta-invalid-key");

  await tester.fill('input[name="key"]', boundKey);
  await tester.locator('form:has(input[name="key"]) button[type="submit"]').click();
  check(await isVisible(tester, "für ein anderes Konto bestimmt", 20000), "email-bound key rejects wrong account");

  await tester.fill('input[name="key"]', key);
  await tester.locator('form:has(input[name="key"]) button[type="submit"]').click();
  await tester.waitForURL(/\/app\/profile\/edit\?welcome=beta/, { timeout: 45000 }).catch(() => {});
  check(
    /\/app\/profile\/edit\?welcome=beta/.test(tester.url()),
    "successful redemption redirects to the guided profile step",
    tester.url(),
  );
  check(await isVisible(tester, "Willkommen in der Private Beta"), "activation card greets the tester");
  check(await isVisible(tester, "noch 30 Tage"), "activation card states the runtime (30 days)");
  check(await isVisible(tester, "Im Beta-Zugang enthalten"), "activation card lists the unlocked features");
  check(await isVisible(tester, "Echte Mitglieder entdecken und gezielt suchen"), "activation card names a networking feature");
  await shot(tester, "08-beta-welcome");

  await fillWelcomeProfile(tester, {
    firstName: "Bea",
    lastName: "Beta (Testkonto)",
    headline: "Founderin (Testkonto)",
    company: "Fiktiv GmbH (fiktiv)",
    location: "Berlin (Testkonto)",
    bio: "Testprofil für den Sprint-15-Lauf – keine echten Daten.",
  });
  check(/\/app\/discover/.test(tester.url()), "profile step continues into /app/discover", tester.url());
  const discoverText = (await tester.locator("main").first().innerText()).replace(/\s+/g, " ");
  check(
    !discoverText.includes("geschlossene Beta") && !discoverText.includes("Beispielprofile"),
    "beta tester sees the real network, not the locked/demo state",
  );
  await shot(tester, "09-beta-discover");

  // Smoke: the tester's core areas load without a login redirect.
  for (const path of ["/app", "/app/profile", "/app/discover", "/app/inbox", "/app/beta"]) {
    const response = await tester.goto(`${BASE}${path}`, { waitUntil: "domcontentloaded" });
    const onLogin = /\/login/.test(new URL(tester.url()).pathname);
    check(Boolean(response) && response.status() < 400 && !onLogin, `tester area loads: ${path}`, `${response?.status()} ${tester.url()}`);
  }
  check(await isVisible(tester, "Dein Beta-Zugang ist aktiv"), "/app/beta now shows the active status card");

  // No admin rights for the tester.
  await tester.goto(`${BASE}/admin/beta`, { waitUntil: "domcontentloaded" }).catch(() => {});
  await tester.waitForURL(/\/app\?denied=admin/, { timeout: 30000 }).catch(() => {});
  check(/denied=admin/.test(tester.url()), "beta tester is refused by /admin/beta", tester.url());

  // A second tester cannot reuse the same key.
  const carlCtx = await newContext();
  const carl = await carlCtx.newPage();
  await register(carl, { first: "Carl", last: "Tester (Testkonto)", email: emails.carl });
  await onboard(carl, ["Startups", "Vertrieb", "Business Development"], "Geschäftspartner finden");
  await carl.goto(`${BASE}/app/beta`);
  await carl.fill('input[name="key"]', key);
  await carl.locator('form:has(input[name="key"]) button[type="submit"]').click();
  check(await isVisible(carl, "Dieser Beta-Schlüssel wurde bereits verwendet", 20000), "used key cannot be redeemed twice");
  await shot(carl, "10-beta-used-key");

  // Complete-profile regression: no redundant profile step after activation.
  await carl.goto(`${BASE}/app/profile/edit`);
  await carl.fill('[name="headline"]', 'Founder (Testkonto)');
  await carl.fill('[name="location"]', 'Berlin');
  await carl.fill('[name="bio"]', 'Complete profile for beta redirect regression.');
  await carl.locator('form:has(input[name="firstName"]) button[type="submit"]').click();
  await carl.waitForURL(/saved=all/, { timeout: 30000 });
  const completeKey = boundKey;
  await carl.goto(`${BASE}/app/beta`);
  await carl.fill('input[name="key"]', completeKey);
  await carl.locator('form:has(input[name="key"]) button[type="submit"]').click();
  await carl.waitForURL(/\/app\/discover\?welcome=beta/, { timeout: 30000 });
  check(true, "complete profile redirects directly to Discover");
  check(true, "email-bound key remains usable by its intended account (case-insensitive)");
  check(await isVisible(carl, "Willkommen in der Private Beta"), "Discover shows activation success");
  check(await isVisible(carl, "noch 30 Tage"), "Discover shows beta duration and expiry");

  // Existing app primitives must follow the same persisted preference.
  for (const mobile of [false, true]) for (const locale of ["de", "en"]) for (const theme of ["light", "dark"]) {
    const ctx = await newContext({ mobile, locale, theme });
    await ctx.addCookies(await carlCtx.cookies());
    const page = await ctx.newPage();
    await page.goto(`${BASE}/app/profile/edit`);
    await page.waitForLoadState("networkidle");
    const style = await page.locator('input[name="headline"]').evaluate(el => ({
      background: getComputedStyle(el).backgroundColor, color: getComputedStyle(el).color,
      border: getComputedStyle(el).borderColor,
    }));
    check(style.background === (theme === "light" ? "rgb(247, 248, 250)" : "rgb(10, 14, 21)"), `app input theme ${mobile}/${locale}/${theme}`, JSON.stringify(style));
    check(await page.locator('a[href="/app/inbox"]').filter({ visible: true }).count() > 0, `app navigation visible ${mobile}/${locale}/${theme}`);
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `app has no horizontal overflow ${mobile}/${locale}/${theme}`);
    await ctx.close();
  }

  await carlCtx.close();
  await resetCtx.close();
  await mailCtx.close();
  await adminCtx.close();
  await testerCtx.close();
} catch (error) {
  results.push({ ok: false, name: "script error", detail: String(error?.stack ?? error) });
  console.error("SCRIPT ERROR:", error);
} finally {
  await browser.close().catch(() => {});
}

/* ------------------------------------------------------------ report */

const failed = results.filter((r) => !r.ok);
writeFileSync(OUT, JSON.stringify({ run: RUN, base: BASE, siteUrl: SITE_URL, total: results.length, failed: failed.length, results }, null, 2));
console.log(`\n${results.length - failed.length}/${results.length} checks passed → ${OUT}`);
if (failed.length > 0) {
  console.log("FAILED:");
  for (const f of failed) console.log(`  · ${f.name} ${f.detail}`);
  process.exit(1);
}
