/**
 * Sprint 12 – browser end-to-end check (Private Beta & real networking).
 *
 * Runs against the REAL Worker build (`npm run cf:build` + `opennextjs-cloudflare
 * preview`, workerd + local D1) with clearly labelled test accounts
 * (`<role>-<run>@innercircle.test`, names end with "(Testkonto)", companies
 * with "(fiktiv)"). It is NOT part of `npm test` and adds no dependency to the
 * project: the browser packages live outside the repository.
 *
 *   mkdir -p /tmp/pw && cd /tmp/pw && npm i playwright-core @sparticuz/chromium
 *   PW_MODULES=/tmp/pw/node_modules BASE_URL=http://127.0.0.1:8787 \
 *     node tests/e2e/sprint12-browser.mjs
 *
 * Requirements: a fresh, isolated LOCAL D1 containing no real users.
 * Do not reset or run this suite against a shared database.
 * `.dev.vars` with ENABLE_DEV_OUTBOX=true and
 * DEV_OUTBOX_RECIPIENTS=@innercircle.test (verification codes are read from the
 * local dev outbox), local D1 migrated + bootstrapped. The script only ever
 * touches the LOCAL database (`wrangler d1 execute --local`) and refuses to
 * run against anything but localhost.
 *
 * Database shortcuts (documented in docs/08-testing.md §3b):
 *   - admin role via the existing `scripts/admin-bootstrap.ts --local`
 *   - redeem-by date of one key, `BetaAccess.endsAt` and afterwards
 *     `Trial.expiresAt` of one tester moved into the past (waiting days is
 *     not possible in a test)
 *   - one test membership (provider "dev") for the paying-member check,
 *     because Stripe is not configured (no payment is simulated anywhere else)
 * Every other SQL statement is read-only.
 *
 * Output: screenshots in preview/sprint12/, results as JSON in $E2E_OUT
 * (default /tmp/e2e-results-<run>.json). Exit code 1 if any check fails.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PW_MODULES = process.env.PW_MODULES ?? "/tmp/pw/node_modules";
const BASE = process.env.BASE_URL ?? "http://127.0.0.1:8787";
const REPO = fileURLToPath(new URL("../..", import.meta.url));
const SHOTS = join(REPO, "preview", "sprint12");
const RUN = String(Date.now());
const OUT = process.env.E2E_OUT ?? `/tmp/e2e-results-${RUN}.json`;
const PASSWORD = "Testing!2026";

if (!/^https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?$/.test(BASE)) {
  console.error(`Refusing to run against ${BASE} – local preview only.`);
  process.exit(2);
}

const { chromium } = await import(pathToFileURL(join(PW_MODULES, "playwright-core", "index.mjs")).href);
const sparticuz = (await import(pathToFileURL(join(PW_MODULES, "@sparticuz", "chromium", "build", "index.js")).href))
  .default;

/* ------------------------------------------------------------ helpers */

const results = [];
function check(ok, name, detail = "") {
  results.push({ ok: Boolean(ok), name, detail: String(detail) });
  console.log(`${ok ? "PASS" : "FAIL"} · ${name}${detail ? ` · ${detail}` : ""}`);
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** Local D1 only. Values in queries are generated by this script, never user input. */
function sql(query) {
  const out = execFileSync("npx", ["wrangler", "d1", "execute", "DB", "--local", "--json", "--command", query], {
    cwd: REPO,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
  return JSON.parse(out).flatMap((entry) => entry.results ?? []);
}

mkdirSync(SHOTS, { recursive: true });
const browser = await chromium.launch({
  executablePath: await sparticuz.executablePath(),
  headless: true,
  // Not sparticuz.args: its --single-process mode loses cookies in a 2nd context.
  args: ["--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu", "--no-zygote"],
});

async function newContext({ mobile = false, locale = "de", theme = "light", storageState } = {}) {
  const context = await browser.newContext({
    viewport: mobile ? { width: 390, height: 844 } : { width: 1440, height: 900 },
    deviceScaleFactor: mobile ? 2 : 1,
    isMobile: mobile,
    hasTouch: mobile,
    colorScheme: theme,
    locale: locale === "de" ? "de-DE" : "en-US",
    storageState,
  });
  await context.addInitScript(
    ([loc, th]) => {
      try {
        localStorage.setItem("ic-locale", loc);
        localStorage.setItem("ic-theme", th);
      } catch {
        /* storage unavailable – defaults apply */
      }
    },
    [locale, theme],
  );
  return context;
}

async function shot(page, name, { fullPage = false } = {}) {
  await page.waitForLoadState("networkidle").catch(() => {});
  await page.waitForTimeout(500);
  await page.screenshot({ path: join(SHOTS, `${name}.png`), fullPage });
}

const visibleText = (page, text) => page.getByText(text, { exact: false }).filter({ visible: true }).first();
async function isVisible(page, text, timeout = 0) {
  if (timeout > 0) {
    try {
      await visibleText(page, text).waitFor({ state: "visible", timeout });
      return true;
    } catch {
      return false;
    }
  }
  return visibleText(page, text).isVisible();
}
const mainText = async (page) => (await page.locator("main").first().innerText()).replace(/\s+/g, " ");
const noHorizontalScroll = (page) =>
  page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1);

async function waitForCode(email) {
  for (let attempt = 0; attempt < 30; attempt++) {
    const rows = sql(`select body from DevOutbox where "to" = '${email}' order by createdAt desc limit 1`);
    const match = rows[0]?.body?.match(/\b(\d{6})\b/);
    if (match) return match[1];
    await sleep(500);
  }
  throw new Error(`no verification code for ${email}`);
}

async function register(page, { first, last, email }) {
  await page.goto(`${BASE}/register`);
  await page.fill('input[name="firstName"]', first);
  await page.fill('input[name="lastName"]', last);
  await page.fill('input[name="email"]', email);
  await page.fill('input[name="password"]', PASSWORD);
  await page.fill('input[name="passwordConfirm"]', PASSWORD);
  await page.check('input[name="age"]');
  await page.check('input[name="terms"]');
  await page.locator('form:has(input[name="firstName"]) button[type="submit"]').click();
  await page.waitForURL(/\/verify/, { timeout: 45000 });
  await page.fill('input[name="code"]', await waitForCode(email));
  await page.locator('form:has(input[name="code"]) button[type="submit"]').first().click();
  await page.waitForURL(/\/onboarding|\/app/, { timeout: 45000 });
}

async function onboard(page, interests, goal) {
  const before = (await page.context().cookies()).find((c) => c.name === "ic_session");
  if (!/\/onboarding/.test(page.url())) await page.goto(`${BASE}/onboarding/interests`);
  for (const label of interests) {
    await page
      .locator("button[aria-pressed]")
      .filter({ hasText: new RegExp(`^\\s*${escapeRegExp(label)}\\s*$`) })
      .first()
      .click();
  }
  await page.locator("button[aria-pressed]").filter({ hasText: goal }).last().click();
  await page.locator('form:has(input[name="startTrial"]) button[type="submit"]').click();
  await page.waitForURL((url) => url.pathname.startsWith("/app"), { timeout: 45000 });
  const after = (await page.context().cookies()).find((c) => c.name === "ic_session");
  check(Boolean(before?.value) && before.value === after?.value && after.httpOnly && after.secure,
    "onboarding preserves the secure HTTP-only session cookie",
    `before=${Boolean(before)}, after=${Boolean(after)}, unchanged=${before?.value === after?.value}, httpOnly=${after?.httpOnly}, secure=${after?.secure}`);
  await page.reload();
  check(new URL(page.url()).pathname.startsWith("/app"), "session survives a hard reload after onboarding");
}

async function login(page, email) {
  await page.goto(`${BASE}/login`);
  await page.fill('input[name="identifier"]', email);
  await page.fill('input[name="password"]', PASSWORD);
  await page.locator('form:has(input[name="identifier"]) button[type="submit"]').click();
  await page.waitForURL((url) => url.pathname.startsWith("/app"), { timeout: 45000 });
}

const keyAlert = (page) => page.locator('form:has(input[name="key"]) [role="alert"]');
async function submitKey(page, key, { navigate = true } = {}) {
  if (navigate) await page.goto(`${BASE}/app/beta`);
  await page.fill('input[name="key"]', key);
  await page.locator('form:has(input[name="key"]) button[type="submit"]').click();
}
async function keyError(page) {
  const alert = keyAlert(page);
  await alert.waitFor({ state: "visible", timeout: 20000 });
  return (await alert.innerText()).trim();
}

async function fillWelcomeProfile(page, fields) {
  for (const [name, value] of Object.entries(fields)) await page.fill(`[name="${name}"]`, value);
  await page.getByRole("button", { name: "Speichern & Netzwerk entdecken" }).click();
  await page.waitForURL(/\/app\/discover/, { timeout: 45000 });
}

async function inboxBadge(page) {
  const links = page.locator('a[href="/app/inbox"]').filter({ visible: true });
  const count = await links.count();
  for (let index = 0; index < count; index++) {
    const match = (await links.nth(index).innerText()).match(/(\d+)/);
    if (match) return Number(match[1]);
  }
  return 0;
}

async function createKey(admin, label) {
  await admin.goto(`${BASE}/admin/beta`);
  await admin.fill('input[name="label"]', `${label} ${RUN}`);
  await admin.getByRole("button", { name: "Schlüssel erstellen" }).click();
  const key = admin.locator('[data-testid="beta-key"]');
  await key.waitFor({ state: "visible", timeout: 20000 });
  return (await key.innerText()).trim();
}

const userId = (email) => sql(`select id from User where email = '${email}'`)[0]?.id;
const handleOf = (email) => sql(`select handle from User where email = '${email}'`)[0]?.handle;

/** Navigate every internal link with the browser session; login redirects are failures. */
async function crawlLinks(page, paths) {
  const hrefs = new Set();
  for (const path of paths) {
    await page.goto(`${BASE}${path}`);
    await page.waitForLoadState("networkidle").catch(() => {});
    const found = await page.evaluate(() =>
      [...document.querySelectorAll('a[href^="/"]')].map((a) => a.getAttribute("href") ?? ""),
    );
    for (const href of found) {
      if (href && !href.startsWith("//") && !href.startsWith("/api/") && !href.startsWith("/_next/")) {
        hrefs.add(href.split("#")[0]);
      }
    }
  }
  const failures = [];
  for (const href of hrefs) {
    // Use the browser: APIRequestContext does not send Secure cookies over
    // local HTTP, whereas Chromium treats loopback as a trustworthy origin.
    const response = await page.goto(`${BASE}${href}`);
    if (!response || response.status() >= 400 || new URL(page.url()).pathname === "/login") {
      failures.push(`${href} → ${response?.status()} ${new URL(page.url()).pathname}`);
    }
  }
  return { total: hrefs.size, failures };
}

/* ------------------------------------------------------------ run */

const emails = Object.fromEntries(
  ["admin", "anna", "ben", "carla", "dora", "mia"].map((role) => [role, `${role}-${RUN}@innercircle.test`]),
);
const dialogs = [];

try {
  // Clean slate for the labelled test data only (local D1).
  sql(
    "DELETE FROM User WHERE email LIKE '%@innercircle.test'; DELETE FROM BetaInvite; DELETE FROM RateLimit; DELETE FROM DevOutbox;",
  );

  /* ---------------------------------------------- admin creates personal keys */
  const adminCtx = await newContext();
  const admin = await adminCtx.newPage();
  await register(admin, { first: "Ada", last: "Admin (Testkonto)", email: emails.admin });
  await onboard(admin, ["Unternehmertum", "Startups", "Investieren"], "Netzwerk aufbauen");
  execFileSync("npx", ["tsx", "scripts/admin-bootstrap.ts", `--email=${emails.admin}`, "--local"], {
    cwd: REPO,
    stdio: "ignore",
  });
  await admin.goto(`${BASE}/admin/beta`);
  check((await admin.locator("h1").first().innerText()).includes("Private Beta"), "admin opens /admin/beta");

  const keys = {};
  keys.anna = await createKey(admin, "E2E Anna");
  await shot(admin, "08-admin-beta-key-created");
  keys.ben = await createKey(admin, "E2E Ben");
  keys.carla = await createKey(admin, "E2E Carla");
  keys.reserve = await createKey(admin, "E2E Reserve (wird deaktiviert)");
  keys.expiring = await createKey(admin, "E2E Einlösefrist (abgelaufen)");
  const allKeys = Object.values(keys);
  check(
    allKeys.every((key) => /^ICB-[0-9A-HJKMNP-TV-Z]{4}(-[0-9A-HJKMNP-TV-Z]{4}){3}$/.test(key)),
    "admin created 5 personal keys in the ICB-XXXX-XXXX-XXXX-XXXX format",
    allKeys.map((key) => `…${key.slice(-4)}`).join(", "),
  );
  const plainHits = allKeys.reduce(
    (sum, key) =>
      sum +
      Number(
        sql(
          `select count(*) as n from BetaInvite where codeHash like '%${key}%' or codeHash like '%${key.replaceAll("-", "")}%' or ifnull(label,'') like '%${key}%'`,
        )[0].n,
      ),
    0,
  );
  const hashRows = sql(`select count(*) as n from BetaInvite where length(codeHash) = 64 and codeHint is not null and label like '% ${RUN}'`)[0].n;
  check(plainHits === 0 && Number(hashRows) === 5, "database stores only a 64-char hash + 4-char hint, never the key", `plain hits: ${plainHits}, hashed rows: ${hashRows}`);

  // Deactivate one unused key through the admin UI; move one redeem-by date into the past.
  await admin.goto(`${BASE}/admin/beta`);
  await admin.locator("li").filter({ hasText: `E2E Reserve (wird deaktiviert) ${RUN}` }).getByRole("button", { name: "Deaktivieren" }).click();
  let reserveStatus = "";
  for (let attempt = 0; attempt < 20 && reserveStatus !== "disabled"; attempt++) {
    await sleep(500);
    reserveStatus = sql(`select status from BetaInvite where label = 'E2E Reserve (wird deaktiviert) ${RUN}'`)[0]?.status;
  }
  check(reserveStatus === "disabled", "admin deactivates an unused key in the UI", `status: ${reserveStatus}`);
  sql(`update BetaInvite set expiresAt = ${Date.now() - 60_000} where label = 'E2E Einlösefrist (abgelaufen) ${RUN}'`);

  /* ---------------------------------------------- testers: register, verify, redeem, profile */
  const annaCtx = await newContext();
  const anna = await annaCtx.newPage();
  await register(anna, { first: "Anna", last: "Keller (Testkonto)", email: emails.anna });
  await onboard(anna, ["Startups", "Vertrieb", "Business Development"], "Geschäftspartner finden");

  // Wrong key first, then the real one typed in lower case with spaces.
  await submitKey(anna, "ICB-2222-3333-4444-5555");
  const annaWrong = await keyError(anna);
  check(/ungültig/i.test(annaWrong), "unknown key → clear error message", annaWrong);
  await anna.fill('input[name="key"]', keys.anna.toLowerCase().replaceAll("-", " "));
  check(!(await keyAlert(anna).isVisible()), "the old error disappears as soon as the key is edited");
  await shot(anna, "03-beta-key-redemption");
  await anna.setViewportSize({ width: 390, height: 844 });
  check(await noHorizontalScroll(anna), "beta key form at 390 px: no horizontal scroll");
  await shot(anna, "03d-beta-key-mobile");
  await anna.setViewportSize({ width: 1440, height: 900 });
  await anna.locator('form:has(input[name="key"]) button[type="submit"]').click();
  await anna.waitForURL(/\/app\/profile\/edit\?welcome=beta/, { timeout: 45000 });
  check(
    (await isVisible(anna, "Willkommen in der Private Beta", 10000)) && (await isVisible(anna, "unter „Discover“")),
    "redeeming (lower case, spaces) grants access at once and opens the guided profile step",
  );
  await shot(anna, "03b-beta-welcome-profile-onboarding");
  await fillWelcomeProfile(anna, {
    headline: "Gründerin · B2B-Software · Leipzig",
    jobTitle: "Gründerin",
    company: "Keller Digital (fiktiv)",
    location: "Leipzig",
    lookingFor: "Vertriebspartner, Pilotkunden",
    offering: "SaaS-Produkt, Produktdemos",
    bio: "Fiktives Testprofil für die Private Beta. Baut eine Software für Angebotsprozesse im Mittelstand.",
  });
  const annaAccess = sql(`select status, endsAt, startsAt from BetaAccess where userId = '${userId(emails.anna)}'`)[0];
  const annaDays = annaAccess ? Math.round((annaAccess.endsAt - annaAccess.startsAt) / 86_400_000) : 0;
  const annaMembership = sql(`select count(*) as n from Membership where userId = '${userId(emails.anna)}'`)[0].n;
  const annaRole = sql(`select role from User where email = '${emails.anna}'`)[0].role;
  check(
    annaAccess?.status === "active" && annaDays === 30 && Number(annaMembership) === 0 && annaRole === "user",
    "beta access = separate 30-day entitlement: no membership row, role stays user",
    `status ${annaAccess?.status}, ${annaDays} days, memberships ${annaMembership}, role ${annaRole}`,
  );

  const benCtx = await newContext();
  const ben = await benCtx.newPage();
  await register(ben, { first: "Ben", last: "Hartmann (Testkonto)", email: emails.ben });
  await onboard(ben, ["Startups", "Vertrieb", "Business Development"], "Kunden finden");
  await submitKey(ben, keys.ben);
  await ben.waitForURL(/welcome=beta/, { timeout: 45000 });
  await fillWelcomeProfile(ben, {
    headline: "Vertrieb für junge Softwarefirmen",
    jobTitle: "Inhaber",
    company: "Hartmann Sales Consulting (fiktiv)",
    location: "Leipzig",
    lookingFor: "SaaS-Produkte, Co-Founder",
    offering: "Pilotkunden, Vertriebspartner, B2B-Vertrieb",
    bio: "Fiktives Testprofil für die Private Beta. Unterstützt junge Softwarefirmen beim Einstieg in den Mittelstand.",
  });

  const carlaCtx = await newContext();
  const carla = await carlaCtx.newPage();
  await register(carla, { first: "Carla", last: "Neumann (Testkonto)", email: emails.carla });
  await onboard(carla, ["Marketing", "Startups", "Content Creation"], "Kapital aufnehmen");
  await submitKey(carla, keys.carla);
  await carla.waitForURL(/welcome=beta/, { timeout: 45000 });
  await fillWelcomeProfile(carla, {
    jobTitle: "Markenberaterin",
    company: "Neumann Brand Studio (fiktiv)",
    location: "Dresden",
    lookingFor: "Investoren, Mentoring",
    offering: "Markenstrategie, Content",
    bio: "Fiktives Testprofil für die Private Beta.",
  });
  const benHandle = handleOf(emails.ben);

  /* ---------------------------------------------- free user: demo only, keys refused */
  const doraCtx = await newContext();
  const dora = await doraCtx.newPage();
  await register(dora, { first: "Dora", last: "Demo (Testkonto)", email: emails.dora });
  await onboard(dora, ["Marketing", "Personal Branding", "Content Creation"], "Netzwerk aufbauen");
  await dora.goto(`${BASE}/app/discover`);
  const doraDiscover = await mainText(dora);
  check(
    doraDiscover.includes("DEMO · Beispielprofil") && doraDiscover.includes("Geschlossene Beta"),
    "free user: Discover shows the labelled demo + closed-beta explanation",
  );
  check(
    !/Hartmann|Keller \(Testkonto\)|Neumann/.test(doraDiscover),
    "free user: no real member appears in the demo deck",
  );
  await shot(dora, "07-discovery-demo-desktop");
  await dora.goto(`${BASE}/app/network`);
  check(!/Hartmann|Keller \(Testkonto\)|Neumann/.test(await mainText(dora)), "free user: no real member in the directory");
  await dora.goto(`${BASE}/app/people/${benHandle}`);
  check(
    !(await mainText(dora)).includes("Unterstützt junge Softwarefirmen"),
    "free user: a real profile URL stays locked (direct call)",
  );
  await dora.goto(`${BASE}/app`);
  await shot(dora, "07b-dashboard-discovery-demo");
  const doraMobileCtx = await newContext({ mobile: true, storageState: await doraCtx.storageState() });
  const doraMobile = await doraMobileCtx.newPage();
  await doraMobile.goto(`${BASE}/app/discover`);
  check(await noHorizontalScroll(doraMobile), "demo Discover at 390 px: no horizontal scroll");
  await shot(doraMobile, "07c-discovery-demo-mobile");
  await doraMobileCtx.close();

  const refusals = [];
  await submitKey(dora, keys.anna);
  refusals.push(["used", await keyError(dora)]);
  await submitKey(dora, keys.reserve);
  refusals.push(["disabled", await keyError(dora)]);
  await shot(dora, "03c-beta-key-disabled-error");
  await submitKey(dora, keys.expiring);
  refusals.push(["expired", await keyError(dora)]);
  check(/bereits verwendet/i.test(refusals[0][1]), "a used key is refused for every other account", refusals[0][1]);
  check(/deaktiviert/i.test(refusals[1][1]), "a deactivated key is refused", refusals[1][1]);
  check(/abgelaufen/i.test(refusals[2][1]), "a key past its redeem-by date is refused", refusals[2][1]);
  // Brute force: 8 attempts per account and hour – 3 used above.
  let limited = "";
  for (let attempt = 4; attempt <= 10 && !limited; attempt++) {
    await submitKey(dora, `ICB-${String(attempt).padStart(4, "7")}-3333-4444-5555`);
    const message = await keyError(dora);
    if (/Zu viele Versuche/i.test(message)) limited = `attempt ${attempt}: ${message}`;
  }
  check(limited.startsWith("attempt 9"), "brute-force protection: the 9th attempt within an hour is blocked", limited || "never limited");
  const doraBeta = sql(`select count(*) as n from BetaAccess where userId = '${userId(emails.dora)}'`)[0].n;
  check(Number(doraBeta) === 0, "no refused attempt created any beta access", `rows: ${doraBeta}`);

  /* ---------------------------------------------- Discover, filters, directory (Anna) */
  await anna.goto(`${BASE}/app/discover`);
  const firstCard = anna.locator("main article").first();
  await firstCard.waitFor({ timeout: 20000 });
  const cardText = (await firstCard.innerText()).replace(/\s+/g, " ");
  check(cardText.includes("Ben Hartmann (Testkonto)"), "Discover: best match is the real member Ben (shared interests, supply ↔ demand)");
  check(!/\d+\s?%/.test(cardText) && !cardText.includes("DEMO"), "Discover: no match percentage, no demo content on real cards");
  const cardBox = await firstCard.boundingBox();
  const mediaBox = await firstCard.locator(".col-span-12").first().boundingBox();
  check(
    Boolean(cardBox && mediaBox && mediaBox.width < cardBox.width * 0.6),
    "Discover desktop: two-column card",
    cardBox && mediaBox ? `${Math.round(mediaBox.width)}/${Math.round(cardBox.width)} px` : "no box",
  );
  await shot(anna, "01-network-discover-desktop");

  // Business-goal filter through the real form, combinable and resettable.
  await anna.getByRole("button", { name: /Mehr Filter/ }).click();
  await anna.locator('select[name="goal"]').selectOption({ label: "Kunden finden" });
  await anna.getByRole("button", { name: "Filtern" }).click();
  await anna.waitForURL(/goal=find-customers/, { timeout: 20000 });
  const goalText = await mainText(anna);
  check(
    goalText.includes("Ben Hartmann") && goalText.includes("Businessziel: Kunden finden") && !goalText.includes("Carla Neumann"),
    "goal filter 'Kunden finden' shows only matching members, with a removable chip",
  );
  await shot(anna, "01c-discover-filter-goal-desktop");
  await anna.goto(`${BASE}/app/discover?goal=find-customers&location=Dresden`);
  check(await isVisible(anna, "Keine Mitglieder passen zu diesen Filtern", 10000), "filters combine (goal AND location) → honest empty state");
  await anna.getByRole("link", { name: "Zurücksetzen" }).first().click();
  await anna.waitForURL((url) => url.pathname === "/app/discover" && url.search === "", { timeout: 20000 });
  check(
    (await anna.locator("main article").first().innerText()).includes("Ben Hartmann"),
    "reset returns to the full, deterministic order",
  );

  await anna.goto(`${BASE}/app/network`);
  const directory = await mainText(anna);
  check(
    directory.includes("Ben Hartmann") && directory.includes("Carla Neumann") && !directory.includes("DEMO"),
    "directory lists the real testers, no demo filler",
  );
  await shot(anna, "01b-network-directory-desktop");

  const annaMobileCtx = await newContext({ mobile: true, storageState: await annaCtx.storageState() });
  const annaMobile = await annaMobileCtx.newPage();
  await annaMobile.goto(`${BASE}/app/discover`);
  check(await noHorizontalScroll(annaMobile), "Discover at 390 px: no horizontal scroll");
  await shot(annaMobile, "02-network-discover-mobile");
  await annaMobile.goto(`${BASE}/app/network`);
  check(await noHorizontalScroll(annaMobile), "directory at 390 px: no horizontal scroll");
  await shot(annaMobile, "02b-network-directory-mobile");

  /* ---------------------------------------------- profile → request → accept → chat */
  await anna.goto(`${BASE}/app/people/${benHandle}`);
  const profileText = await mainText(anna);
  check(
    profileText.includes("Hartmann Sales Consulting (fiktiv)") && profileText.includes("Unterstützt junge Softwarefirmen"),
    "real member profile shows the tester's own data",
  );
  await shot(anna, "04-real-member-profile");
  await annaMobile.goto(`${BASE}/app/people/${benHandle}`);
  check(await noHorizontalScroll(annaMobile), "member profile at 390 px: no horizontal scroll");
  await shot(annaMobile, "04c-real-member-profile-mobile");
  const annaDarkCtx = await newContext({ locale: "en", theme: "dark", storageState: await annaCtx.storageState() });
  const annaDark = await annaDarkCtx.newPage();
  await annaDark.goto(`${BASE}/app/people/${benHandle}`);
  await shot(annaDark, "04b-real-member-profile-dark-en");

  const requestMessage = "Hallo Ben, dein Fokus auf Pilotkunden passt gut zu unserem Produkt – kurzer Austausch?";
  await anna.goto(`${BASE}/app/discover`);
  await anna.getByRole("button", { name: "Kontakt anfragen" }).filter({ visible: true }).first().click();
  await anna.locator('textarea[name="message"]').fill(requestMessage);
  await anna.getByRole("button", { name: "Anfrage senden" }).click();
  await sleep(1500);
  await anna.goto(`${BASE}/app/people/${benHandle}`);
  await anna.reload();
  check(await isVisible(anna, "Anfrage gesendet", 10000), "'Anfrage gesendet' persists after reload");
  const pendingRows = sql(
    `select count(*) as n from ConnectionRequest where fromUserId = '${userId(emails.anna)}' and toUserId = '${userId(emails.ben)}' and status = 'pending'`,
  )[0].n;
  check(Number(pendingRows) === 1, "exactly one stored request with the message", `pending rows: ${pendingRows}`);

  await ben.goto(`${BASE}/app`);
  const benBadge = await inboxBadge(ben);
  check(benBadge === 1, "recipient sees the new request as inbox badge 1", `badge: ${benBadge}`);
  await ben.goto(`${BASE}/app/inbox?tab=requests`);
  check(await isVisible(ben, requestMessage.slice(0, 40), 15000), "incoming request shows sender + personal message");
  await shot(ben, "05-incoming-request");
  await ben.setViewportSize({ width: 390, height: 844 });
  check(await noHorizontalScroll(ben), "incoming request at 390 px: no horizontal scroll");
  await shot(ben, "05b-incoming-request-mobile");
  await ben.setViewportSize({ width: 1440, height: 900 });
  await ben.getByRole("button", { name: "Annehmen" }).filter({ visible: true }).first().click();
  await ben.waitForURL(/tab=messages&c=/, { timeout: 30000 });
  const conversationId = new URL(ben.url()).searchParams.get("c");
  check(await isVisible(ben, requestMessage.slice(0, 40), 15000), "accepting opens the chat with the request message");
  await shot(ben, "06-chat-after-accept");
  const benNotes = sql(`select type, readAt from Notification where userId = '${userId(emails.ben)}'`);
  const requestNotes = benNotes.filter((row) => row.type === "connection_request");
  check(
    requestNotes.length === 1 && requestNotes[0].readAt !== null && !benNotes.some((row) => row.type === "message"),
    "one request notice, resolved on accept – no duplicate or per-message notifications",
    benNotes.map((row) => `${row.type}${row.readAt ? "✓" : ""}`).join(", "),
  );
  await ben.goto(`${BASE}/app`);
  check((await inboxBadge(ben)) === 0, "after accepting, the recipient's badge is back to 0");

  // Anna keeps the chat open; Ben's reply must arrive by polling, without reload.
  anna.on("dialog", (dialog) => {
    dialogs.push(dialog.message());
    dialog.dismiss().catch(() => {});
  });
  ben.on("dialog", (dialog) => {
    dialogs.push(dialog.message());
    dialog.dismiss().catch(() => {});
  });
  await anna.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  const reply = "Danke Anna! Donnerstag 10 Uhr passt mir gut.";
  await ben.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  await ben.locator("textarea#composer-3").fill(reply);
  await ben.locator("form:has(textarea#composer-3) button[type='submit']").click();
  check(await isVisible(anna, "Donnerstag 10 Uhr passt", 30000), "reply arrives in the open chat by polling (no reload)");
  await anna.goto(`${BASE}/app/inbox?tab=messages`);
  const inboxList = await mainText(anna);
  check(inboxList.includes("Ben Hartmann") && inboxList.includes("Donnerstag 10 Uhr"), "inbox lists the partner with a message preview");

  const payload = "<img src=x onerror=alert(document.domain)>";
  await anna.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  await anna.locator("textarea#composer-3").fill(payload);
  await anna.locator("form:has(textarea#composer-3) button[type='submit']").click();
  await ben.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  const literal = await isVisible(ben, payload, 15000);
  check(literal && dialogs.length === 0, "HTML in a message is shown as text, never executed (XSS)", `dialogs: ${dialogs.length}`);

  await anna.goto(`${BASE}/app/people/${benHandle}`);
  await anna.getByRole("link", { name: /^Nachricht/ }).first().click();
  await anna.waitForURL(/tab=messages/, { timeout: 20000 });
  await visibleText(anna, "Donnerstag 10 Uhr passt").waitFor({ timeout: 15000 });
  const pairChats = sql(
    `select count(*) as n from Conversation c where exists (select 1 from ConversationParticipant p where p.conversationId = c.id and p.userId = '${userId(emails.anna)}') and exists (select 1 from ConversationParticipant p where p.conversationId = c.id and p.userId = '${userId(emails.ben)}')`,
  )[0].n;
  check(Number(pairChats) === 1, "'Nachricht' from the profile opens the same chat – one conversation per pair", `conversations: ${pairChats}`);

  await carla.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  check(
    !(await mainText(carla)).includes("Donnerstag 10 Uhr") && !carla.url().includes(conversationId),
    "a third account cannot open the chat (redirected, nothing revealed)",
  );

  await dora.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  check(!(await mainText(dora)).includes("Donnerstag 10 Uhr") && !dora.url().includes(conversationId),
    "free demo account cannot open another pair's protected chat");
  const privatePayloads = await dora.evaluate(async ([handle, chat]) => {
    const paths = ["/app/discover", "/app/network", `/app/people/${handle}`,
      `/app/inbox?tab=messages&c=${chat}`];
    return Promise.all(paths.map(async (path) => {
      const response = await fetch(path, { headers: { RSC: "1" } });
      return { path, status: response.status, body: await response.text() };
    }));
  }, [benHandle, conversationId]);
  check(privatePayloads.every(({ status, body }) => status === 200 &&
    !body.includes("Hartmann Sales Consulting") && !body.includes("Unterstützt junge Softwarefirmen") &&
    !body.includes("Donnerstag 10 Uhr")),
    "free demo account: direct RSC fetches reveal no private profile or chat content",
    `${privatePayloads.length} protected routes checked`);

  await annaMobile.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  await visibleText(annaMobile, "Donnerstag 10 Uhr passt").waitFor({ timeout: 15000 });
  check(await noHorizontalScroll(annaMobile), "chat at 390 px: no horizontal scroll");
  await shot(annaMobile, "06b-chat-mobile");
  await annaDark.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  await visibleText(annaDark, "Donnerstag 10 Uhr passt").waitFor({ timeout: 15000 });
  const sendLabel = await annaDark.locator("form:has(textarea#composer-3) button[type='submit']").innerText();
  check(sendLabel.trim() === "Send", "English UI renders the chat (EN labels)", `button: ${sendLabel.trim()}`);
  await shot(annaDark, "06c-chat-dark-en");
  await anna.goto(`${BASE}/app`);
  await shot(anna, "10-dashboard-beta-desktop");

  /* ---------------------------------------------- paying member is unaffected */
  const miaCtx = await newContext();
  const mia = await miaCtx.newPage();
  await register(mia, { first: "Mia", last: "Mitglied (Testkonto)", email: emails.mia });
  await onboard(mia, ["Startups", "Investieren", "Vertrieb"], "Geschäftspartner finden");
  const now = Date.now();
  sql(
    `insert into Membership (id, userId, plan, status, provider, priceCents, currency, currentPeriodStart, currentPeriodEnd, cancelAtPeriodEnd, startedAt, createdAt, updatedAt) values ('e2e-membership-${RUN}', '${userId(emails.mia)}', 'monthly', 'active', 'dev', 2499, 'EUR', ${now}, ${now + 30 * 86_400_000}, 0, ${now}, ${now}, ${now})`,
  );
  await mia.goto(`${BASE}/app/discover`);
  const miaDiscover = await mainText(mia);
  check(
    /Ben Hartmann|Anna Keller|Carla Neumann/.test(miaDiscover) && !miaDiscover.includes("DEMO · Beispielprofil"),
    "paying member sees the real network without any key",
  );
  await mia.goto(`${BASE}/app/beta`);
  check(
    (await isVisible(mia, "Du brauchst keinen Beta-Schlüssel", 10000)) && (await mia.locator('input[name="key"]').count()) === 0,
    "paying member: /app/beta explains no key is needed (no form, key stays unused)",
  );
  await shot(mia, "11-member-no-key-needed");
  await mia.goto(`${BASE}/app/opportunities`);
  check(!(await mainText(mia)).includes("Discovery-Demo"), "paying member keeps the real business areas (no demo mode)");
  const miaBeta = sql(`select count(*) as n from BetaAccess where userId = '${userId(emails.mia)}'`)[0].n;
  check(Number(miaBeta) === 0, "paying member never gets a beta row");

  /* ---------------------------------------------- admin-only, unauthenticated */
  const deniedFor = [];
  for (const path of ["/admin", "/admin/beta", "/admin/users", "/admin/investments", "/admin/applications"]) {
    for (const [who, page] of [
      ["tester", anna],
      ["member", mia],
    ]) {
      await page.goto(`${BASE}${path}`);
      if (!page.url().includes("denied=admin")) deniedFor.push(`${who} ${path} → ${page.url()}`);
    }
  }
  check(deniedFor.length === 0, "every /admin route redirects testers and members (server-side)", deniedFor.join("; ") || "10/10 redirected");
  await anna.goto(`${BASE}/dev/outbox`);
  const outboxText = await anna.locator("body").innerText();
  check(!/\b\d{6}\b/.test(outboxText) && !outboxText.includes("@innercircle.test"), "dev outbox never shows codes or recipients to a non-admin");
  const anonCtx = await newContext();
  const anon = await anonCtx.newPage();
  const anonRedirects = [];
  for (const path of ["/app/discover", "/app/inbox?tab=messages", "/app/beta", "/admin/beta"]) {
    await anon.goto(`${BASE}${path}`);
    if (!/\/login/.test(anon.url())) anonRedirects.push(`${path} → ${anon.url()}`);
  }
  check(anonRedirects.length === 0, "without a session every app/admin route redirects to login", anonRedirects.join("; ") || "4/4");
  await anonCtx.close();

  /* ---------------------------------------------- admin overview, revoke */
  await admin.goto(`${BASE}/admin/beta`);
  const adminText = await mainText(admin);
  check(
    adminText.includes("Anna Keller") && adminText.includes("Ben Hartmann") && adminText.includes("Carla Neumann") && !adminText.includes("Mia Mitglied"),
    "admin sees the three redeemed testers (not the member) with period and actions",
  );
  await shot(admin, "08b-admin-beta-management", { fullPage: true });
  const carlaRow = admin.locator("li").filter({ hasText: "Carla Neumann" });
  await carlaRow.getByRole("button", { name: "Vorzeitig beenden" }).click();
  await carlaRow.locator("form").getByRole("button", { name: "Vorzeitig beenden" }).click();
  let carlaStatus = "";
  for (let attempt = 0; attempt < 20 && carlaStatus !== "revoked"; attempt++) {
    await sleep(500);
    carlaStatus = sql(`select status from BetaAccess where userId = '${userId(emails.carla)}'`)[0]?.status;
  }
  check(carlaStatus === "revoked", "admin revokes a tester early", `status: ${carlaStatus}`);

  /* ---------------------------------------------- after revocation (Carla) */
  await carla.goto(`${BASE}/app/discover`);
  const carlaDiscover = await mainText(carla);
  check(carlaDiscover.includes("Dein Beta-Zugang wurde beendet"), "revoked: Discover explains the end of the beta");
  check(!/Hartmann|Keller \(Testkonto\)|Anna Keller/.test(carlaDiscover), "revoked: no real members in Discover");
  await shot(carla, "09-beta-ended-locked");
  await carla.goto(`${BASE}/app/network`);
  check(!/Ben Hartmann|Anna Keller/.test(await mainText(carla)), "revoked: no real members in the directory");
  await carla.goto(`${BASE}/app/people/${benHandle}`);
  check(!(await mainText(carla)).includes("Unterstützt junge Softwarefirmen"), "revoked: real profiles locked");
  await carlaCtx.clearCookies();
  await login(carla, emails.carla);
  await carla.goto(`${BASE}/app/discover`);
  check(
    (await mainText(carla)).includes("Dein Beta-Zugang wurde beendet"),
    "a new session (cookies cleared, fresh login) does not restore the access",
  );

  /* ---------------------------------------------- after expiry (Ben) */
  sql(`update BetaAccess set endsAt = ${Date.now() - 60_000} where userId = '${userId(emails.ben)}'`);
  await ben.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  check(await isVisible(ben, "Donnerstag 10 Uhr passt", 15000), "expired: chat history stays readable");
  check((await ben.locator('textarea[name="body"]').filter({ visible: true }).count()) === 0, "expired: no message composer");
  await shot(ben, "09b-beta-expired-chat-readonly");
  await ben.goto(`${BASE}/app/discover`);
  const benDiscover = await mainText(ben);
  check(benDiscover.includes("abgelaufen") && !benDiscover.includes("Anna Keller"), "expired: Discover shows the expiry notice, no real members");
  // The contact list lives in the inbox (network pages are locked after the beta).
  await ben.goto(`${BASE}/app/inbox?tab=requests&sub=connections`);
  check((await mainText(ben)).includes("Anna Keller"), "expired: existing contacts are kept (inbox → contacts)");
  await anna.goto(`${BASE}/app/discover`);
  check(!(await mainText(anna)).includes("Ben Hartmann (Testkonto)"), "an expired tester is no longer suggested to others");
  // Realistic end state: 30 days later the 48-h demo is long over as well.
  sql(`update Trial set expiresAt = ${Date.now() - 60_000} where userId = '${userId(emails.ben)}'`);
  await ben.goto(`${BASE}/app/discover`);
  const benLocked = await mainText(ben);
  check(
    benLocked.includes("Dein Beta-Zugang ist abgelaufen") &&
      !benLocked.includes("DEMO · Beispielprofil") &&
      !benLocked.includes("Anna Keller") &&
      (await ben.getByRole("link", { name: "Zum Posteingang" }).count()) > 0,
    "expired after the demo: locked page with end notice, link to contacts/inbox – no demo, no members",
  );
  await shot(ben, "09c-beta-expired-after-demo");
  await ben.goto(`${BASE}/app/network`);
  check(!(await mainText(ben)).includes("Anna Keller"), "expired after the demo: directory locked as well");

  // Documented behaviour (not a lock): an active contact can still write to an expired tester.
  await anna.goto(`${BASE}/app/inbox?tab=messages&c=${conversationId}`);
  const annaComposer = await anna.locator("textarea#composer-3").isVisible();
  console.log(`INFO · active contact can still write to the expired tester: ${annaComposer ? "yes" : "no"}`);

  /* ---------------------------------------------- dead links (tester + demo user) */
  const appPages = [
    "/app",
    "/app/discover",
    "/app/network",
    "/app/inbox",
    "/app/inbox?tab=requests",
    "/app/inbox?tab=messages",
    "/app/profile",
    "/app/profile/edit",
    "/app/beta",
    "/app/settings",
    "/app/billing",
    "/app/events",
    "/app/opportunities",
    "/app/jobs",
    "/app/investments",
    "/app/marketplace",
    "/app/learn",
  ];
  for (const [who, page] of [
    ["tester", anna],
    ["demo user", dora],
  ]) {
    const { total, failures } = await crawlLinks(page, appPages);
    check(failures.length === 0, `no dead internal links for the ${who}`, failures.join("; ") || `${total} links OK`);
  }
} catch (error) {
  check(false, "scenario aborted", error instanceof Error ? error.stack ?? error.message : String(error));
} finally {
  await browser.close();
  const passed = results.filter((result) => result.ok).length;
  writeFileSync(OUT, JSON.stringify({ run: RUN, base: BASE, passed, total: results.length, results }, null, 2));
  console.log(`\n${passed}/${results.length} checks passed (run ${RUN}) → ${OUT}`);
  process.exitCode = passed === results.length ? 0 : 1;
}
